spring:
  sql:
    init:
      mode: never
      encoding: UTF-8

  datasource:
    url: jdbc:postgresql://192.168.0.105:5432/jpa2
    username: slava
    password: 2012
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

    defer-datasource-initialization: true